//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EETLibrary.EET {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2006.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EETSOAP", Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public partial class EETService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback OdeslaniTrzbyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EETService() {
            this.Url = global::EETLibrary.Properties.Settings.Default.EETLibrary_EET_EETService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event OdeslaniTrzbyCompletedEventHandler OdeslaniTrzbyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fs.mfcr.cz/eet/OdeslaniTrzby", RequestElementName="Trzba", RequestNamespace="http://fs.mfcr.cz/eet/schema/v3", ResponseElementName="Odpoved", ResponseNamespace="http://fs.mfcr.cz/eet/schema/v3", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Hlavicka")]
        public OdpovedHlavickaType OdeslaniTrzby(TrzbaHlavickaType Hlavicka, TrzbaDataType Data, TrzbaKontrolniKodyType KontrolniKody, [System.Xml.Serialization.XmlElementAttribute("Chyba", typeof(OdpovedChybaType))] [System.Xml.Serialization.XmlElementAttribute("Potvrzeni", typeof(OdpovedPotvrzeniType))] out object Item, [System.Xml.Serialization.XmlElementAttribute("Varovani")] out OdpovedVarovaniType[] Varovani) {
            object[] results = this.Invoke("OdeslaniTrzby", new object[] {
                        Hlavicka,
                        Data,
                        KontrolniKody});
            Item = ((object)(results[1]));
            Varovani = ((OdpovedVarovaniType[])(results[2]));
            return ((OdpovedHlavickaType)(results[0]));
        }
        
        /// <remarks/>
        public void OdeslaniTrzbyAsync(TrzbaHlavickaType Hlavicka, TrzbaDataType Data, TrzbaKontrolniKodyType KontrolniKody) {
            this.OdeslaniTrzbyAsync(Hlavicka, Data, KontrolniKody, null);
        }
        
        /// <remarks/>
        public void OdeslaniTrzbyAsync(TrzbaHlavickaType Hlavicka, TrzbaDataType Data, TrzbaKontrolniKodyType KontrolniKody, object userState) {
            if ((this.OdeslaniTrzbyOperationCompleted == null)) {
                this.OdeslaniTrzbyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOdeslaniTrzbyOperationCompleted);
            }
            this.InvokeAsync("OdeslaniTrzby", new object[] {
                        Hlavicka,
                        Data,
                        KontrolniKody}, this.OdeslaniTrzbyOperationCompleted, userState);
        }
        
        private void OnOdeslaniTrzbyOperationCompleted(object arg) {
            if ((this.OdeslaniTrzbyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OdeslaniTrzbyCompleted(this, new OdeslaniTrzbyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2006.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public partial class TrzbaHlavickaType {
        
        private string uuid_zpravyField;
        
        private System.DateTime dat_odeslField;
        
        private bool prvni_zaslaniField;
        
        private bool overeniField;
        
        private bool overeniFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuid_zpravy {
            get {
                return this.uuid_zpravyField;
            }
            set {
                this.uuid_zpravyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime dat_odesl {
            get {
                return this.dat_odeslField;
            }
            set {
                this.dat_odeslField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool prvni_zaslani {
            get {
                return this.prvni_zaslaniField;
            }
            set {
                this.prvni_zaslaniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool overeni {
            get {
                return this.overeniField;
            }
            set {
                this.overeniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool overeniSpecified {
            get {
                return this.overeniFieldSpecified;
            }
            set {
                this.overeniFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2006.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public partial class OdpovedVarovaniType {
        
        private int kod_varovField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int kod_varov {
            get {
                return this.kod_varovField;
            }
            set {
                this.kod_varovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2006.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public partial class OdpovedChybaType {
        
        private int kodField;
        
        private bool testField;
        
        private bool testFieldSpecified;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int kod {
            get {
                return this.kodField;
            }
            set {
                this.kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool test {
            get {
                return this.testField;
            }
            set {
                this.testField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool testSpecified {
            get {
                return this.testFieldSpecified;
            }
            set {
                this.testFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2006.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public partial class OdpovedPotvrzeniType {
        
        private string fikField;
        
        private bool testField;
        
        private bool testFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fik {
            get {
                return this.fikField;
            }
            set {
                this.fikField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool test {
            get {
                return this.testField;
            }
            set {
                this.testField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool testSpecified {
            get {
                return this.testFieldSpecified;
            }
            set {
                this.testFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2006.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public partial class OdpovedHlavickaType {
        
        private string uuid_zpravyField;
        
        private string bkpField;
        
        private System.DateTime dat_prijField;
        
        private bool dat_prijFieldSpecified;
        
        private System.DateTime dat_odmitField;
        
        private bool dat_odmitFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuid_zpravy {
            get {
                return this.uuid_zpravyField;
            }
            set {
                this.uuid_zpravyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bkp {
            get {
                return this.bkpField;
            }
            set {
                this.bkpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime dat_prij {
            get {
                return this.dat_prijField;
            }
            set {
                this.dat_prijField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dat_prijSpecified {
            get {
                return this.dat_prijFieldSpecified;
            }
            set {
                this.dat_prijFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime dat_odmit {
            get {
                return this.dat_odmitField;
            }
            set {
                this.dat_odmitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dat_odmitSpecified {
            get {
                return this.dat_odmitFieldSpecified;
            }
            set {
                this.dat_odmitFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2006.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public partial class BkpElementType {
        
        private BkpDigestType digestField;
        
        private BkpEncodingType encodingField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BkpDigestType digest {
            get {
                return this.digestField;
            }
            set {
                this.digestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BkpEncodingType encoding {
            get {
                return this.encodingField;
            }
            set {
                this.encodingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2006.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public enum BkpDigestType {
        
        /// <remarks/>
        SHA1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2006.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public enum BkpEncodingType {
        
        /// <remarks/>
        base16,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2006.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public partial class PkpElementType {
        
        private PkpDigestType digestField;
        
        private PkpCipherType cipherField;
        
        private PkpEncodingType encodingField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PkpDigestType digest {
            get {
                return this.digestField;
            }
            set {
                this.digestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PkpCipherType cipher {
            get {
                return this.cipherField;
            }
            set {
                this.cipherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PkpEncodingType encoding {
            get {
                return this.encodingField;
            }
            set {
                this.encodingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2006.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public enum PkpDigestType {
        
        /// <remarks/>
        SHA256,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2006.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public enum PkpCipherType {
        
        /// <remarks/>
        RSA2048,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2006.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public enum PkpEncodingType {
        
        /// <remarks/>
        base64,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2006.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public partial class TrzbaKontrolniKodyType {
        
        private PkpElementType pkpField;
        
        private BkpElementType bkpField;
        
        /// <remarks/>
        public PkpElementType pkp {
            get {
                return this.pkpField;
            }
            set {
                this.pkpField = value;
            }
        }
        
        /// <remarks/>
        public BkpElementType bkp {
            get {
                return this.bkpField;
            }
            set {
                this.bkpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2006.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public partial class TrzbaDataType {
        
        private string dic_poplField;
        
        private string dic_poverujicihoField;
        
        private int id_provozField;
        
        private string id_poklField;
        
        private string porad_cisField;
        
        private System.DateTime dat_trzbyField;
        
        private decimal celk_trzbaField;
        
        private decimal zakl_nepodl_dphField;
        
        private bool zakl_nepodl_dphFieldSpecified;
        
        private decimal zakl_dan1Field;
        
        private bool zakl_dan1FieldSpecified;
        
        private decimal dan1Field;
        
        private bool dan1FieldSpecified;
        
        private decimal zakl_dan2Field;
        
        private bool zakl_dan2FieldSpecified;
        
        private decimal dan2Field;
        
        private bool dan2FieldSpecified;
        
        private decimal zakl_dan3Field;
        
        private bool zakl_dan3FieldSpecified;
        
        private decimal dan3Field;
        
        private bool dan3FieldSpecified;
        
        private decimal cest_sluzField;
        
        private bool cest_sluzFieldSpecified;
        
        private decimal pouzit_zboz1Field;
        
        private bool pouzit_zboz1FieldSpecified;
        
        private decimal pouzit_zboz2Field;
        
        private bool pouzit_zboz2FieldSpecified;
        
        private decimal pouzit_zboz3Field;
        
        private bool pouzit_zboz3FieldSpecified;
        
        private decimal urceno_cerp_zuctField;
        
        private bool urceno_cerp_zuctFieldSpecified;
        
        private decimal cerp_zuctField;
        
        private bool cerp_zuctFieldSpecified;
        
        private int rezimField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dic_popl {
            get {
                return this.dic_poplField;
            }
            set {
                this.dic_poplField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dic_poverujiciho {
            get {
                return this.dic_poverujicihoField;
            }
            set {
                this.dic_poverujicihoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id_provoz {
            get {
                return this.id_provozField;
            }
            set {
                this.id_provozField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id_pokl {
            get {
                return this.id_poklField;
            }
            set {
                this.id_poklField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string porad_cis {
            get {
                return this.porad_cisField;
            }
            set {
                this.porad_cisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime dat_trzby {
            get {
                return this.dat_trzbyField;
            }
            set {
                this.dat_trzbyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal celk_trzba {
            get {
                return this.celk_trzbaField;
            }
            set {
                this.celk_trzbaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal zakl_nepodl_dph {
            get {
                return this.zakl_nepodl_dphField;
            }
            set {
                this.zakl_nepodl_dphField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakl_nepodl_dphSpecified {
            get {
                return this.zakl_nepodl_dphFieldSpecified;
            }
            set {
                this.zakl_nepodl_dphFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal zakl_dan1 {
            get {
                return this.zakl_dan1Field;
            }
            set {
                this.zakl_dan1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakl_dan1Specified {
            get {
                return this.zakl_dan1FieldSpecified;
            }
            set {
                this.zakl_dan1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan1 {
            get {
                return this.dan1Field;
            }
            set {
                this.dan1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan1Specified {
            get {
                return this.dan1FieldSpecified;
            }
            set {
                this.dan1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal zakl_dan2 {
            get {
                return this.zakl_dan2Field;
            }
            set {
                this.zakl_dan2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakl_dan2Specified {
            get {
                return this.zakl_dan2FieldSpecified;
            }
            set {
                this.zakl_dan2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan2 {
            get {
                return this.dan2Field;
            }
            set {
                this.dan2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan2Specified {
            get {
                return this.dan2FieldSpecified;
            }
            set {
                this.dan2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal zakl_dan3 {
            get {
                return this.zakl_dan3Field;
            }
            set {
                this.zakl_dan3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakl_dan3Specified {
            get {
                return this.zakl_dan3FieldSpecified;
            }
            set {
                this.zakl_dan3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan3 {
            get {
                return this.dan3Field;
            }
            set {
                this.dan3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan3Specified {
            get {
                return this.dan3FieldSpecified;
            }
            set {
                this.dan3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal cest_sluz {
            get {
                return this.cest_sluzField;
            }
            set {
                this.cest_sluzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cest_sluzSpecified {
            get {
                return this.cest_sluzFieldSpecified;
            }
            set {
                this.cest_sluzFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pouzit_zboz1 {
            get {
                return this.pouzit_zboz1Field;
            }
            set {
                this.pouzit_zboz1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pouzit_zboz1Specified {
            get {
                return this.pouzit_zboz1FieldSpecified;
            }
            set {
                this.pouzit_zboz1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pouzit_zboz2 {
            get {
                return this.pouzit_zboz2Field;
            }
            set {
                this.pouzit_zboz2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pouzit_zboz2Specified {
            get {
                return this.pouzit_zboz2FieldSpecified;
            }
            set {
                this.pouzit_zboz2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pouzit_zboz3 {
            get {
                return this.pouzit_zboz3Field;
            }
            set {
                this.pouzit_zboz3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pouzit_zboz3Specified {
            get {
                return this.pouzit_zboz3FieldSpecified;
            }
            set {
                this.pouzit_zboz3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal urceno_cerp_zuct {
            get {
                return this.urceno_cerp_zuctField;
            }
            set {
                this.urceno_cerp_zuctField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool urceno_cerp_zuctSpecified {
            get {
                return this.urceno_cerp_zuctFieldSpecified;
            }
            set {
                this.urceno_cerp_zuctFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal cerp_zuct {
            get {
                return this.cerp_zuctField;
            }
            set {
                this.cerp_zuctField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cerp_zuctSpecified {
            get {
                return this.cerp_zuctFieldSpecified;
            }
            set {
                this.cerp_zuctFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int rezim {
            get {
                return this.rezimField;
            }
            set {
                this.rezimField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2006.0")]
    public delegate void OdeslaniTrzbyCompletedEventHandler(object sender, OdeslaniTrzbyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2006.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OdeslaniTrzbyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OdeslaniTrzbyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OdpovedHlavickaType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OdpovedHlavickaType)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public object Item {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public OdpovedVarovaniType[] Varovani {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OdpovedVarovaniType[])(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591